endpoints:
  restart:
    enabled: true
    sensitive: false



info:
  build:
    name: ${name}
    description: ${description}
    version: ${version}
    springBootVersion: ${springBootVersion}
    test: ${test}
